### ISSUE TITLE
spreadsheet-to-cpplib v0.1.6 failes

### ISSUE THREAD

**Issue by shajeen** [shajeen/spreadsheet-to-cpplib#5]
found the error,

```sh
(env) root@DESKTOP-IV22R5K:~/build_test# spreadsheet-to-cpplib --file="file_example_XLSX_5000.xlsx"
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|S|p|r|e|a|d|S|h|e|e|t|-|t|o|-|c|p|p|l|i|b|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

Below sheets are found,

Answer [yes/no] for below questions.
1) Do you want Mathametical Expression library support for formula calculation ?: : yes
2) Configure as header-only library ? :: no
3) Get default value from formula as double.? :: yes
4) Make string as 0.0?. :: yes

Working please wait........
Traceback (most recent call last):
  File "/root/build_test/env/bin/spreadsheet-to-cpplib", line 8, in <module>
    sys.exit(main())
  File "/root/build_test/env/lib/python3.8/site-packages/spreadsheet_to_cpplib/main.py", line 6, in main
    argumet.run_cli_interface()
  File "/root/build_test/env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/build_test/env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/build_test/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/build_test/env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/build_test/env/lib/python3.8/site-packages/spreadsheet_to_cpplib/run.py", line 16, in run_cli_interface
    fileOperations.process_xlsm_file(file)
  File "/root/build_test/env/lib/python3.8/site-packages/spreadsheet_to_cpplib/fileOperations.py", line 79, in process_xlsm_file
    copy_math_lib()
  File "/root/build_test/env/lib/python3.8/site-packages/spreadsheet_to_cpplib/fileOperations.py", line 23, in copy_math_lib
    shutil.copy(DATA_PATH, 'output/src/exprtk.hpp')
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/build_test/env/lib/python3.8/site-packages/spreadsheet_to_cpplib/libcpp/exprtk.hpp'
(env) root@DESKTOP-IV22R5K:~/build_test#
```

**Comment by shajeen** [comment]
![2](https://user-images.githubusercontent.com/2623563/123547680-59107000-d77f-11eb-8cb1-d05e8e8b9932.PNG)

fixed, implemented in spreadSheet-to-cpplib 1.0.0v
